### ISSUE TITLE
Rootfs not found

### ISSUE THREAD

**Issue by hanafym** [colcon/colcon-hardware-acceleration#22]
Hey all, I am trying to run the following command: colcon acceleration linux preempt_rt --install-dir install-kr260
but I am getting the following error:
SECURITY WARNING: This class invokes explicitly a shell via the shell=True argument of the Python subprocess library, and uses admin privileges to manage raw disk images. It is the user's responsibility to ensure that all whitespace and metacharacters passed are quoted appropriately to avoid shell injection vulnerabilities.
**Rootfs at /home/vboxuser/krs_ws/acceleration/firmware/select/rootfs.cpio.gz not found.**

Does anyone know where the missing file may be located?

**Comment by vmayoral** [comment]
There's nothing missing, `rootfs.cpio.gz` is one of the artifacts that should ship with firmware packages like https://github.com/ros-acceleration/acceleration_firmware_kr260. See `alpha` and `beta` releases for more details.

This compress artifact includes the rootfs that is then transformed as part of the cross-compilation process and later used to create the SD card to get your accelerated application operational.

If you're relying on KRS, refer to that repo.
